repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix --exit-non-zero-on-fix
        language: system
        types: [python]
        require_serial: true

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [python]
        require_serial: true